//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttestationType
    {
        public AttestationType()
        {
            this.Subject = new HashSet<Subject>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<Subject> Subject { get; set; }
    }
}
