//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarksType
    {
        public MarksType()
        {
            this.Attestation = new HashSet<Attestation>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Attestation> Attestation { get; set; }
    }
}
